# .yaml files can be used by teams to setup hub ports
# see the example below
 ports:
    servo-ports:
        0:
            {"name":"type"}
        1:
        2:
        3:
        4:
        5:
    motor-ports:
        0:
            {"name": "type", "encoder": bool}
        1:
        2:
        3:
    analog-ports:
        0:
          {"name": "type"}
        1:
    digital-ports:
        0:
          {"name": "type"}
        1:
        2:
        3:
    I2C-buses:
        I2C-bus-1-ports:
            0:
              {"name": "type"}
            1:
            2:
            3:
    UART-ports:
        0:
          bool
        1:
        2:
        3:
    
